version: '3.8'

services:

  db:
    image: postgres:15.3
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: len0xx
      POSTGRES_PASSWORD: DatabasePassword
    ports:
      - 5400:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  frontend:
    image: len0xx/blog-front
    container_name: frontend
    build: ./frontend
    restart: on-failure:10
    depends_on:
      - backend
    environment:
      BACKEND_PROTOCOL: http
      BACKEND_CONTAINER: backend
      BACKEND_PORT: 8000
      NEST_ACCESS_TOKEN: kq8An2hu7S7v9S9j39ZnD8CDj5SakevSj2e06SjbS8An0a7ancs4A9c3mSjsSVD29z7v
      NEXTAUTH_SECRET: nEis8Sbne9cja0ASj8Cj2JCA1c8Aj0lbvA09cka89Zn3Vnjs8SVj0zmsViV01n28VjksnZ7
      NEXTAUTH_URL: http://blog.local
    ports:
      - 4000:3000

  backend:
    image: len0xx/blog-nest
    container_name: backend
    build: ./backend
    restart: on-failure:10
    depends_on:
      - db
    environment:
      PORT: 8000
      NEST_ACCESS_TOKEN: kq8An2hu7S7v9S9j39ZnD8CDj5SakevSj2e06SjbS8An0a7ancs4A9c3mSjsSVD29z7v
      AUTH_SECRET: Bjev6Suis8sVjdi8ssvnz8xjvs7vn329SVjb7dbfnd8dJjvjhvs8svh2vj495bj5sdfv3vbhvsjd
      DATABASE_URL: postgresql://len0xx:DatabasePassword@db:5432/blog?schema=public
    ports:
      - 8080:8000

  images:
    image: len0xx/blog-nest-images
    container_name: images
    build: ./images
    restart: on-failure:10
    depends_on:
      - backend
    environment:
      PORT: 8000
    ports:
      - 8100:8000
    volumes:
      - static_files:/backend/files
    
  nginx:
    image: len0xx/blog-nginx
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - frontend
    ports:
      - 80:80
    volumes:
      - static_files:/static

volumes:
  static_files:
