apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: blog
  POSTGRES_USER: len0xx
  POSTGRES_PASSWORD: DatabasePassword
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: db
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:15.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: blog
        - name: POSTGRES_USER
          value: len0xx
        - name: POSTGRES_PASSWORD
          value: DatabasePassword
