apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    nodePort: 31555
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: len0xx/blog-front:latest
        imagePullPolicy: Always
        env:
        - name: BACKEND_PROTOCOL
          value: http
        - name: BACKEND_CONTAINER
          value: backend
        - name: BACKEND_PORT
          value: "8000"
        ports:
        - containerPort: 3000
          protocol: TCP
